In [1]:
print("Hola Mundo")

Hola Mundo

Hola Mundo

In [ ]:
import os
print(os.path.exists(os.getenv("GOOGLE_APPLICATION_CREDENTIALS")))
print(os.getenv("GOOGLE_APPLICATION_CREDENTIALS"))

In [ ]:
from google.cloud import bigquery
from dotenv import load_dotenv
import os

load_dotenv()

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")

project_id = os.getenv("GCP_PROJECT_ID")
dataset_id = os.getenv("BQ_DATASET_ID")

client = bigquery.Client(project=project_id)

In [ ]:
tables = client.list_tables("shopnow")
for t in tables:
    print(t.table_id)

In [ ]:
GOOGLE_APPLICATION_CREDENTIALS=C:\\Users\\Usuario\\Desktop\\Curso_DS\\clave_json\\tc-novarix-data.json
GCP_PROJECT_ID=tc-novarix-data
BQ_DATASET_ID=shopnow

In [3]:
from faker import Faker
import pandas as pd
import random

fake = Faker()
rows = []

for _ in range(10):
    rows.append({
        "customer_id": fake.uuid4(),
        "name": fake.name(),
        "email": fake.email(),
        "phone": fake.phone_number(),
        "address": fake.address().replace("\n", ", "),
        "created_at": fake.date_time_between(start_date="-2y", end_date="now")
    })

df = pd.DataFrame(rows)
df.to_csv("customers_fake.csv", index=False)

In [4]:
df

,customer_id,name,email,phone,address,created_at
0,ba73e73f-1371-479b-be48-2f117f83b78a,Mr. Michael Chaney DVM,dicksonkimberly@example.net,367.760.7156x7571,"07377 Donovan Mission, Alvarezbury, PR 12731",2025-05-29 10:42:40
1,4ac99ece-7947-45d2-81ea-14b4a1b28634,James Smith,iferguson@example.net,511.582.2969x2191,"5180 Diana Shoal Suite 923, Dennisfurt, NV 40096",2025-11-29 11:43:34
2,c430a3b3-c579-45b8-98c5-70dc242044ac,Pam Love,rcampbell@example.org,233.480.3836,"31299 Jacqueline Haven Apt. 016, Lake Timothys...",2025-08-13 13:23:20
3,e6f51b55-c313-4bc0-966b-dda151ed1d43,Anthony Herrera,sarahmendoza@example.net,309-634-0731,"6122 Hines Estates, Rachaelchester, OR 39975",2025-01-15 10:57:06
4,05a3f9eb-233c-45b5-ac7f-a6703f50b094,John Elliott,bobby81@example.org,751.951.6250x745,"6837 Mark Walks, Lindaport, MO 59956",2025-08-29 14:22:48
5,4259f871-8df4-4680-8e85-65aaa017b5f3,Robert King,barrysmith@example.com,511-895-0604x6141,"391 Miller Parkway Suite 312, Heathtown, OR 15321",2025-10-25 23:44:19
6,a40b0068-8612-4889-ab6b-41d632e02bb1,James Johnson,moodykristin@example.org,(861)893-3608,"46586 Cannon Road Apt. 262, East Patrickfurt, ...",2024-12-17 10:36:19
7,50df2b1d-e14d-4808-8715-664b8d5ac3ad,Paul Lopez,katelyncastro@example.net,(522)493-4343x64903,"15674 Alexander Garden, Transhire, AZ 31094",2025-10-16 17:21:25
8,ecc64018-c223-498f-8ecc-46d7c560c1b6,Chelsey Warner,nicole23@example.org,+1-846-762-5186,"055 Gonzalez Lake, New Briannatown, TX 20264",2025-01-26 05:55:25
9,050b03af-357b-4d35-ae66-2f61402f0e69,Rhonda Wilson,wesley16@example.net,593-636-7892,"6898 Eugene Coves, Taylorview, MT 08244",2025-04-12 00:09:43

In [5]:
from faker import Faker
import pandas as pd
import random

fake = Faker()
rows = []

for i in range(1, 11):   # 10 filas
    rows.append({
        "customer_id": i,   # INTEGER
        "name": fake.name(),
        "email": fake.email(),
        "phone": fake.random_number(digits=9, fix_len=True),  # número de 9 dígitos
        "address": fake.address().replace("\n", ", "),
        "created_at": fake.date_time_between(start_date="-2y", end_date="now")
    })

df = pd.DataFrame(rows)
df.to_csv("customers_fake.csv", index=False)
df

,customer_id,name,email,phone,address,created_at
0,1,Michael Carpenter,matthew94@example.com,844115674,"6621 Arias Unions, West Ashleeborough, MS 45686",2025-01-26 00:47:52
1,2,Wendy Jenkins,gabrielallen@example.com,567006001,"36503 Julia Port Suite 401, Port Caitlinview, ...",2026-04-14 23:18:03
2,3,Earl Collins,eddieallen@example.net,540389996,"Unit 4637 Box 4805, DPO AA 50133",2025-02-13 14:34:23
3,4,Peter Gordon,marissa09@example.org,582755369,"837 Jeffrey Tunnel Apt. 011, East Seth, VI 63643",2025-09-20 22:24:44
4,5,Samuel Baker,carolynhicks@example.net,130660734,"7829 Anita Gateway, Shawstad, UT 17125",2024-09-10 16:08:44
5,6,James Robinson,veronicapope@example.net,907963538,"79515 Melanie Passage, Justinfort, MH 68559",2024-05-17 05:56:44
6,7,Joseph Skinner,kristina60@example.org,249658005,"469 Christine Meadow, Kendraland, IA 83491",2025-04-19 17:25:08
7,8,Joshua Chavez,pattonnancy@example.org,895611545,"295 Harper Street Apt. 577, Shannonhaven, OK 8...",2025-09-08 03:30:27
8,9,Thomas Castaneda,williamsdaniel@example.com,121680407,"Unit 4422 Box 1050, DPO AP 41840",2025-01-06 03:03:02
9,10,Laura Bernard,elizabeth60@example.net,936208233,"892 Jones Crescent Suite 334, Michaelhaven, DC...",2025-04-27 12:40:32